replicaCount: 1

image:
  repository: laur1314/php-store
  pullPolicy: IfNotPresent
  tag: 1.0.0


service:
  type: NodePort
  port: 80
  targetport: 80

container:
  name: ecommerce
  volumes:
    name: app
  volumeMounts:
    name: app
    mountPath: /var/www/html/

mysql:
  auth:
    username: user
    rootPassword: test
    password: user
    database: store
  ports:
    port: 3306
    primary:
  persistence:
    existingClaim: mysql
  volumePermissions:
    enabled: true
  initdbScripts:
    init_script.sh: |
    #!/bin/bash
    
  # volumes:
  #   name: mysql
  #   persistentVolumeClaim:
  #     claimName: mysql
  # volumeMounts:
  #   name: mysql
  #   mountPath: /var/www/html/data/ecommerce.sql

environments:
  DB_HOST: prod-mysql
  DB_NAME: store
  DB_USERNAME: user
  DB_PASSWORD: user
  APP_URL: http://ecommerce.local/
  # APP_ENV: production

ingress:
  enabled: true

  hosts:
    - host: ecommerce.local
      paths:
        - path: /
          pathType: ImplementationSpecific