replicaCount: 1

image:
  repository: laur1314/php-store
  pullPolicy: IfNotPresent
  tag: latest


service:
  type: NodePort
  port: 80
  targetport: 80

container:
  name: ecommerce

mysql:
  auth:
    username: user
    rootPassword: test
    password: user
    database: store
  ports:
    port: 3306
environments:
  DB_HOST: prod-mysql
  DB_NAME: store
  DB_USERNAME: user
  DB_PASSWORD: user
  APP_URL: http://ecommerce.local/
  # APP_ENV: production

ingress:
  enabled: true

  hosts:
    - host: ecommerce.local
      paths:
        - path: /
          pathType: ImplementationSpecific