apiVersion: v1
kind: PersistentVolume
metadata:
  name: database
spec:
  claimRef:
    namespace: default
    name: mysql
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
    